apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "twist-product.fullname" . }}-mongo-config
data:
  mongo-host: {{ .Values.mongo.host | quote }}
  mongo-port: {{ .Values.mongo.port | quote }}