apiVersion: v1
name: techtwist-profile
description: A Helm chart for deploying the TechTwist.Profile Spring Boot application to AKS.
type: application
version: 0.1.0
appVersion: "1.0.0" # Replace with your application version if different
# Ensure all Kubernetes manifests in the templates directory have a valid `apiVersion`.