apiVersion: v2
name: techtwist-profile
description: A Helm chart for deploying the TechTwist.Profile Spring Boot application to AKS.
type: application
version: 0.1.0
appVersion: "1.0.0"

# values.yaml
# Default values for techtwist-profile.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: crostonj/techtwist-profile
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx" # Or your ingress controller class
  annotations:
    kubernetes.io/ingress.class: nginx # Or your ingress controller
    # kubernetes.io/tls-acme: "true" # Enable cert-manager for automatic TLS (if needed)
  hosts:
    - host: techtwist-profile.techtwist.com # Replace with your domain
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: techtwist-profile-tls # Replace with your TLS secret name (if using TLS)
      hosts:
        - techtwist-profile.techtwist.com

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: TECHTWIST_PROFILE_ENV
    value: "production" # Change this to your desired environment variable
  - name: TABLENAME
    value: UserProfile
  - name: ACCOUNTNAME
    value: techtwistdatastorage
  - name: ACCOUNTKEY
    valueFrom:
      secretKeyRef:
        name: accountkey
        key: accountkey
  # Add your environment variables here
  # Example:
  # - name: SPRING_DATASOURCE_URL
  #   value: "jdbc:postgresql://postgres:5432/mydb"
  # - name: SPRING_DATASOURCE_USERNAME
  #   value: "user"
  # - name: SPRING_DATASOURCE_PASSWORD
  #   value: "password"